services:
  php:
    volumes:
      - ../fewohbee:/var/www/html/fewohbee:cached
  web:
    volumes:
      - ../fewohbee:/var/www/html/fewohbee:cached
  cron:
    volumes:
      - ../fewohbee:/var/www/html/fewohbee:cached